name: news_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  flutter_bloc: ^5.0.1
  firebase_core: ^0.4.5
  toast: ^0.1.5
  bot_toast: ^3.0.0
  http: ^0.12.2
  animations: ^1.1.1
  flutter_webview_plugin: ^0.3.11
  google_fonts: ^1.1.0
  modal_progress_hud: ^0.1.3
  pie_chart:
  web_scraper:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
